# Generated by Django 4.1.7 on 2023-05-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_price', models.IntegerField()),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
