# Generated by Django 4.2 on 2023-05-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduser',
            old_name='Credit_Balance',
            new_name='credit_balance',
        ),
        migrations.RenameField(
            model_name='enduser',
            old_name='Loan_Balance',
            new_name='loan_balance',
        ),
        migrations.RenameField(
            model_name='enduser',
            old_name='School_ID',
            new_name='school_id',
        ),
    ]
