# Generated by Django 4.2 on 2023-05-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0002_rename_credit_balance_enduser_credit_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
