# Generated by Django 4.2 on 2023-06-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0002_initialize_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_logs',
            name='pos_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_balance_logs', to='me_pays_app.pos'),
        ),
    ]
