# Generated by Django 4.2 on 2023-06-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0002_initialize_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('desc', models.CharField(max_length=255)),
                ('account_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balance_logs', to='me_pays_app.enduser')),
                ('cashier_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_balance_logs', to='me_pays_app.cashier')),
                ('enduser_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_balance_logs', to='me_pays_app.enduser')),
            ],
        ),
    ]
