# Generated by Django 4.2 on 2023-05-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0002_initialize_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pos',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
