# Generated by Django 4.2 on 2023-05-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0002_initialize_groups'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table=None,
        ),
    ]
