# Generated by Django 4.2 on 2023-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0003_alter_admin_contact_number_alter_pos_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
