# Generated by Django 4.2 on 2023-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0003_alter_balance_logs_account_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
