# Generated by Django 4.2 on 2023-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0003_balance_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_logs',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
