# Generated by Django 4.2 on 2023-05-11 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0003_alter_menu_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='menu_owner'),
        ),
    ]
