# Generated by Django 4.2 on 2023-05-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0004_menu_menu_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
