# Generated by Django 4.2 on 2023-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0004_alter_cashier_credit_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pos',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
