# Generated by Django 4.2 on 2023-06-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0005_alter_enduser_credit_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
