# Generated by Django 4.2 on 2023-06-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me_pays_app', '0008_alter_order_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='enduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='me_pays_app.enduser'),
        ),
    ]
